package main

import (
	"log"
	"webtool-api/endpoints"
	"webtool-api/middleware"

	"github.com/gofiber/fiber/v2"

	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"

	//----- SWAGGER -----

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "webtool-api/docs"
)

/**
 *
 * @author A.Dequilla
 *
 */

// @title Webtool
// @version 2.0
// @description KPLUS Webtool Swagger
// @termsOfService http://swagger.io/terms/
// @contact.name FDSAP-A.Dequilla
// @contact.email alex.dequilla@fortress-asya.com
// @license.name
// @license.url
// @host 10.21.0.66:1111
// @BasePath /
func main() {
	middleware.PostgreSQLConnect()
	app := fiber.New()

	app.Use(logger.New())
	endpoints.ViewSearch(app)
	endpoints.SlelectbyCid(app)
	endpoints.Edit(app)
	endpoints.Delete(app)

	app.Use(cors.New(cors.Config{
		AllowCredentials: true,
	}))

	log.Fatal(app.Listen(":1111"))
}
