package main

import (
	"log"
	"webtool-api/controller"
	"webtool-api/middleware"

	"github.com/gofiber/fiber/v2"

	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"

	//----- SWAGGER -----
	swagger "github.com/arsmn/fiber-swagger/v2"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "webtool-api/docs"
)

// @title Webtool
// @version 2.0
// @description KPLUS Webtool Swagger
// @termsOfService http://swagger.io/terms/
// @contact.name FDSAP-A.Dequilla
// @contact.email alex.dequilla@fortress-asya.com
// @license.name
// @license.url
// @host 192.168.0.148:1111
// @BasePath /
func main() {
	middleware.PostgreSQLConnect()
	app := fiber.New()

	app.Use(logger.New())
	AppRoutes(app)

	app.Use(cors.New(cors.Config{
		AllowCredentials: true,
	}))

	log.Fatal(app.Listen(":1111"))
}

func AppRoutes(app *fiber.App) {
	// Swagger
	app.Get("/docs/*", swagger.HandlerDefault)
	//-----

	//Login/Authenticated/Logout
	app.Post("/Login/", controller.Login)
	app.Post("/Authenticate/", controller.Authenticated)
	app.Post("/Logout/", controller.Logout)

	//Administration
	app.Post("/get_usermanagement/", controller.GetUserManagements)
	app.Post("/get_rolesmanagement/", controller.GetRolesManagements)
	app.Post("/get_hierarchy/", controller.GetHierarchy)

	//Enrollment
	app.Post("/get_listforregistration/", controller.GetListforRegistration)

	//Monitoring
	app.Post("/get_clientprofile/", controller.GetClientProfile)
	app.Post("/get_remittancelog/", controller.GetRemittanceLog)
	app.Post("/get_remittancestatus/", controller.GetRemittanceStatus)
	app.Post("/get_smslog/", controller.GetSmsLog)
	app.Post("/get_transactionLog/", controller.GetTransLog)
	app.Post("/get_listuseddevice/", controller.GetUsedDevice)
	app.Post("/get_failedenrollment/", controller.GetFailedEnrollment)
	app.Post("/get_listofagent/", controller.GetListofAgent)

	//Utilities
	app.Post("/get_feestructure/", controller.GetFeeStructure)
	app.Post("/get_paramconfig/", controller.GetParamConfig)
	app.Post("/get_atmloc/", controller.GetAtmLoc)
	app.Post("/get_banknews/", controller.GetBankNews)
	app.Post("/get_productservices/", controller.GetProductServices)
	app.Post("/get_servicedowntime/", controller.GetServiceDowntime)
	app.Post("/get_insti/", controller.GetInstitution)
	app.Post("/get_branch/", controller.GetBranch)
	app.Post("/get_unit/", controller.GetUnit)
	app.Post("/get_center/", controller.GetCenter)
	app.Post("/get_provider/", controller.GetProvider)
	app.Post("/get_producttype/", controller.GetProductType)
	app.Post("/get_productcategory/", controller.GetProductCategory)
	app.Post("/get_billerproduct/", controller.GetBillerProduct)
	app.Post("/get_loadproduct/", controller.GetLoadProduct)
	app.Post("/get_commission/", controller.GetCommission)
	app.Post("/get_banklist/", controller.GetBankList)
	app.Post("/get_partnerlist/", controller.GetPartnerList)
	app.Post("/get_splashscreen/", controller.GetSplashScreen)

	///CustomerService
	app.Post("/get_csrhotline/", controller.GetCsrHotline)
	app.Post("/get_concerntype/", controller.GetConcernType)

}
